# -*- coding: utf-8 -*-
"""Text Summariser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/Michaelzats/Text-Summariser/blob/main/Text_Summariser.ipynb

#Text Summariser

The following tool summarises the input text or text from web articles.
"""

# !pip3 install transformers torch sentencepiece

from transformers import pipeline
import requests
from bs4 import BeautifulSoup

#insert the website where you want to get the information from
url = "https://www.theguardian.com/world/live/2022/jun/02/russia-ukraine-war-latest-zelenskiy-says-243-children-so-far-killed-in-war-russia-claims-latest-us-weapons-package-is-direct-provocation-live"
r = requests.get(url)
soup = BeautifulSoup(r.text, 'html.parser')
paragraphs = soup.find_all('p')

text = [paragraph.text for paragraph in paragraphs]
words = ' '.join(text).split(' ')[:400]
ARTICLE = ' '.join(words)
# ARTICLE

# using pipeline API for summarization task
summarization = pipeline("summarization")
original_text = ARTICLE #or you can insert your own text with ""
summary_text = summarization(original_text)[0]['summary_text']
print("Summary:", summary_text)